/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_livre.View;

import java.sql.SQLException;
import pj_livre.Controller.C_livre;

/**
 *
 * @author razanateraa
 */
public class V_Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger= java.util.logging.Logger.getLogger(V_Main.class.getName());

    private final C_livre leControleurl;

    public void afficher() {
        setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form V_Main
     */
    public V_Main(C_livre leControleurl) throws Exception {
        initComponents();
        this.leControleurl = leControleurl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mb_menu = new javax.swing.JMenuBar();
        mn_quitter = new javax.swing.JMenu();
        mi_accueil = new javax.swing.JMenu();
        mn_direction = new javax.swing.JMenu();
        mi_livre = new javax.swing.JMenuItem();
        mn_gestion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mn_quitter.setText("Quitter");
        mn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_quitterActionPerformed(evt);
            }
        });
        mb_menu.add(mn_quitter);

        mi_accueil.setText("Accueil");
        mb_menu.add(mi_accueil);

        mn_direction.setText("Direction");

        mi_livre.setText("Livre");
        mi_livre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_livreActionPerformed(evt);
            }
        });
        mn_direction.add(mi_livre);

        mb_menu.add(mn_direction);

        mn_gestion.setText("Gestion");
        mb_menu.add(mn_gestion);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_quitterActionPerformed
        setVisible(false);
        exit();
    }//GEN-LAST:event_mn_quitterActionPerformed

    private void mi_livreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_livreActionPerformed
        try {
            leControleurl.aff_V_livre();
        } catch (SQLException ex) {
            System.getLogger(V_Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_livreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws Exception {
        C_livre leControleurl = new C_livre();
        System.out.print(leControleurl);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenu mi_accueil;
    private javax.swing.JMenuItem mi_livre;
    private javax.swing.JMenu mn_direction;
    private javax.swing.JMenu mn_gestion;
    private javax.swing.JMenu mn_quitter;
    // End of variables declaration//GEN-END:variables

    private void exit() {
    System.exit(0);
}

}
